---
title: "BRM parallel - tests"
output: html_notebook
---

Next step: copy testing code from stanmodeldev

```{r}
library(tidyverse)
library(parallel)
library(brms)
library(cmdstanr)

options(mc.cores = parallel::detectCores(), brms.backend = "cmdstanr")
cache_dir <- here::here("local_temp_data")
if(!dir.exists(cache_dir)) {
  dir.create(cache_dir)
}
source(here::here("R", "brm_parallel.R"))


```



```{r}
  simple_model_code = "
    data {
      real x[5];
    }
    parameters {
      real mu;
    }
    model {
      x ~ normal(mu, 1);
    }
    "
  simple_model = cmdstan_model(write_stan_file(simple_model_code))

  second_simple_model = cmdstan_model(write_stan_file("
    data {
      real x[7];
    }
    parameters {
      real<lower=0> sigma;
    }
    model {
      x ~ normal(0, sigma);
    }
    "))

  
  num_data = 10
  per_fit_list = list()
  for(i in 1:num_data) {
    per_fit_list[[i]] = list(data = list(x = rnorm(5, i, 1)))
  }

  res <-  sampling_multi2(args_shared = list(model = simple_model), args_per_fit = per_fit_list)

  res
```

```{r}
  per_fit_list2 <- list()
  for(i in 1:num_data) {
    if(i < num_data / 2) {
        per_fit_list2[[i]] <- list(model = simple_model, data = list(x = rnorm(5, i, 1)))
    } else {
        per_fit_list2[[i]] <- list(model = second_simple_model, data = list(x = rnorm(7, i, 1)))
    }
  }

  res = sampling_multi2(args_shared = list(), args_per_fit = per_fit_list2)

  res

```



```{r}
args_per_fit  <- list(
    list(data = data.frame(y = rnorm(10), x = rnorm(10))),
    list(data = data.frame(y = 3 + rnorm(10), x = rnorm(10)))
)

all_fits <- brm_


```

